version: '3.8'
services:
  # this app
  goaway:
    image: "ganjaaa/go-away"
    build: .
    networks:
      - traefik
  # Test Container
  app:
    image: "nginxdemos/hello"
    labels:
      - traefik.enable=true
      - traefik.http.routers.my-app.entrypoints=web
      - traefik.http.routers.my-app.rule=Host(`my.awesome-app.de`)
      - traefik.http.services.my-app.loadbalancer.server.port=80
      # Middleware for this app
      - traefik.http.routers.my-app.middlewares=my-app-blocklist
      - traefik.http.middlewares.my-app-blocklist.forwardauth.address=http://goaway:8080/auth
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
